/* ********* Import script of Holmes Murphy-Brookshire for RedShift ********************************* 
client name		:	Holmes Murphy (Brokshire)
client id		:	
File Type		:	Medical
Layout			:	Tab Delimited
Create date		:	December 2015
Create by		:	Shiwa Bastola				
****************************************************************************** */
-- creating rtemp table
drop table if exists raw_tfk.rtemp_medical;
create table raw_tfk.rtemp_medical(records varchar(max),
sourcefilename varchar(200));

copy raw_tfk.rtemp_medical(records)
from 's3://incoming-das-scrub/traffk/20170224/Enervest/BCBSTX/dEnervestTraffkClaims.txt' 
CREDENTIALS 'aws_access_key_id=AKIAITGBWJRTKONRK4XQ;aws_secret_access_key=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';

update raw_tfk.rtemp_medical
set sourcefilename = 'dEnervestTraffkEligibility.txt'
where sourcefilename is null;

drop table if exists raw_tfk.raw_medical_enervest;
create table raw_tfk.raw_medical_enervest(
Account_Number varchar(200),
Claim_Number varchar(200),
Claim_Extention varchar(200),
Line_Number varchar(200),
Line_of_Business_Code varchar(200),		
First_Date_of_Service varchar(200),
Paid_Date varchar(200),
Debit_Credit_Code varchar(200),
Member_Key varchar(200),
Disposition_Code varchar(200),
Group_Number varchar(200),
Section_Number varchar(200),
Subscriber_ID varchar(200),
Subscriber_SSN varchar(200),
Patient_DOB varchar(200),
Patient_SSN varchar(200),
Patient_Gender varchar(200),
Patient_Relationship varchar(200),
Patient_First_Name varchar(200),
Patient_Middle_Name varchar(200),
Patient_Last_Name varchar(200),
Patient_Zip_Code varchar(200),
Medicare_Primary_Indicator varchar(200),
Ineligible_Reason_Code_1 varchar(200),
Ineligible_Reason_Code_2 varchar(200),
Ineligible_Reason_Code_3 varchar(200),
Last_Date_of_Service varchar(200),
Admission_Date varchar(200),
Discharge_Date varchar(200),
Received_Date varchar(200),
Claim_Reporting_Category varchar(200),
Policy_Type_Code varchar(200),
Claim_Origin_Code varchar(200),
CCP_Program_Indicator varchar(200),
CCP_Requirement_MET_code varchar(200),
Diagnosis_Classification_Code varchar(200),
Diagnosis_Category_Code varchar(200),
Diagnosis_Code_1 varchar(200),
Diagnosis_Code_2 varchar(200),
Diagnosis_Code_3 varchar(200),
Diagnosis_Code_4 varchar(200),
Diagnosis_Code_5 varchar(200),
HCPCS_CPT_Code varchar(200),
Revenue_Code varchar(200),
ICD10_Indicator varchar(200),
ICD9_Procedure_Code_1 varchar(200),
ICD9_Procedure_Code_2 varchar(200),
ICD9_Procedure_Code_3 varchar(200),
Place_of_Treatment varchar(200),
Type_of_Service varchar(200),
DRG varchar(200),
MDC varchar(200),
Patient_Status varchar(200),
Payment_Tier_Code varchar(200),
Services varchar(200),
Admission_Indicator varchar(200),
Day_Count varchar(200),
Visit_Indicator varchar(200),
Billed_Amount varchar(200),
Ineligible_Amount varchar(200),
Eligible_Amount varchar(200),
Deductible_Amount varchar(200),
Coinsurance_Amount varchar(200),
Copay_Amount varchar(200),
Paid_Amount varchar(200),
National_Access_Fee varchar(200),
Surcharge_Amount varchar(200),
IL_ADP_Discount varchar(200),
Allowed_Amount varchar(200),
Medicare_Paid_Amount varchar(200),
Workers_Compensation_Amount varchar(200),
All_Other_Payer_Amount varchar(200),
HCA_Draft_Amount varchar(200),
Claim_Filing_Code varchar(200),
Adjustment_Sequence_Number varchar(200),
Procedure_Code_Modifier varchar(200),
Payee_Code varchar(200),
Bill_Type_Class_Code varchar(200),
Bill_Frequency_Code varchar(200),
Bill_Institutional_Code varchar(200),
Provider_Network varchar(200),
Billing_Provider_Number varchar(200),
Billing_Provider_Tax_ID varchar(200),
Billing_National_Provider_Identifier varchar(200),
Billing_Provider_Name varchar(200),
Billing_Provider_Address_Line_1 varchar(200),
Billing_Provider_Address_Line_2 varchar(200),
Billing_Provider_City varchar(200),
Billing_Provider_State varchar(200),
Billing_Provider_Zip_Code varchar(200),
Performing_Provider_Number varchar(200),
Performing_Provider_Tax_ID varchar(200),
Performing_National_Provider_Identifier varchar(200),
Performing_Provider_Name varchar(200),
Performing_Provider_Specialty varchar(200),
Performing_Provider_Type_Code varchar(200),
Performing_Provider_Participation_Level varchar(200),
Performing_Provider_Address_Line_1 varchar(200),
Performing_Provider_Address_Line_2 varchar(200),
Performing_Provider_City varchar(200),
Performing_Provider_State varchar(200),
Performing_Provider_Zip_Code varchar(200),
Prescribing_Physician_First_Name varchar(200),
Prescribing_Physician_Last_Name varchar(200),
RX_ID varchar(200),
RX_National_Drug_Code varchar(200),
RX_Drug_Name varchar(200),
RX_Drug_Type_Code varchar(200),
RX_Drug_Category_Code varchar(200),
RX_Tier_Level_Code varchar(200),
RX_Therapeutic_Class varchar(200),
RX_DEA_Number varchar(200),
RX_Mail_Order_Indicator varchar(200),
RX_Dispense_as_Written varchar(200),
RX_Ingredient_Cost_Amount varchar(200),
RX_Dispensing_Fee_Amount varchar(200),
RX_Sales_Tax varchar(200),
RX_Metric_Quantity varchar(200),
RX_Days_Supply varchar(200),
RX_Origin_Code varchar(200),
RX_GPI varchar(200),
RX_Generic_Paid_Indicator varchar(200),
Rx_Chain_Pharmacy_ID varchar(200),
Rx_Formulary_Drug_Indicator varchar(200),
RX_Compound_Code varchar(200),
RX_Copay_differential_amount varchar(200),
Filler varchar(200),
sourcefilename varchar(200)
);

insert into raw_tfk.raw_medical_enervest(
Account_Number,
Claim_Number,
Claim_Extention,
Line_Number,
Line_of_Business_Code,
First_Date_of_Service,
Paid_Date,
Debit_Credit_Code,
Member_Key,
Disposition_Code,
Group_Number,
Section_Number,
Subscriber_ID,
Subscriber_SSN,
Patient_DOB,
Patient_SSN,
Patient_Gender,
Patient_Relationship,
Patient_First_Name,
Patient_Middle_Name,
Patient_Last_Name,
Patient_Zip_Code,
Medicare_Primary_Indicator,
Ineligible_Reason_Code_1,
Ineligible_Reason_Code_2,
Ineligible_Reason_Code_3,
Last_Date_of_Service,
Admission_Date,
Discharge_Date,
Received_Date,
Claim_Reporting_Category,
Policy_Type_Code,
Claim_Origin_Code,
CCP_Program_Indicator,
CCP_Requirement_MET_code,
Diagnosis_Classification_Code,
Diagnosis_Category_Code,
Diagnosis_Code_1,
Diagnosis_Code_2,
Diagnosis_Code_3,
Diagnosis_Code_4,
Diagnosis_Code_5,
HCPCS_CPT_Code,
Revenue_Code,
ICD10_Indicator,
ICD9_Procedure_Code_1,
ICD9_Procedure_Code_2,
ICD9_Procedure_Code_3,
Place_of_Treatment,
Type_of_Service,
DRG,
MDC,
Patient_Status,
Payment_Tier_Code,
Services,
Admission_Indicator,
Day_Count,
Visit_Indicator,
Billed_Amount,
Ineligible_Amount,
Eligible_Amount,
Deductible_Amount,
Coinsurance_Amount,
Copay_Amount,
Paid_Amount,
National_Access_Fee,
Surcharge_Amount,
IL_ADP_Discount,
Allowed_Amount,
Medicare_Paid_Amount,
Workers_Compensation_Amount,
All_Other_Payer_Amount,
HCA_Draft_Amount,
Claim_Filing_Code,
Adjustment_Sequence_Number,
Procedure_Code_Modifier,
Payee_Code,
Bill_Type_Class_Code,
Bill_Frequency_Code,
Bill_Institutional_Code,
Provider_Network,
Billing_Provider_Number,
Billing_Provider_Tax_ID,
Billing_National_Provider_Identifier,
Billing_Provider_Name,
Billing_Provider_Address_Line_1,
Billing_Provider_Address_Line_2,
Billing_Provider_City,
Billing_Provider_State,
Billing_Provider_Zip_Code,
Performing_Provider_Number,
Performing_Provider_Tax_ID,
Performing_National_Provider_Identifier,
Performing_Provider_Name,
Performing_Provider_Specialty,
Performing_Provider_Type_Code,
Performing_Provider_Participation_Level,
Performing_Provider_Address_Line_1,
Performing_Provider_Address_Line_2,
Performing_Provider_City,
Performing_Provider_State,
Performing_Provider_Zip_Code,
Prescribing_Physician_First_Name,
Prescribing_Physician_Last_Name,
RX_ID,
RX_National_Drug_Code,
RX_Drug_Name,
RX_Drug_Type_Code,
RX_Drug_Category_Code,
RX_Tier_Level_Code,
RX_Therapeutic_Class,
RX_DEA_Number,
RX_Mail_Order_Indicator,
RX_Dispense_as_Written,
RX_Ingredient_Cost_Amount,
RX_Dispensing_Fee_Amount,
RX_Sales_Tax,
RX_Metric_Quantity,
RX_Days_Supply,
RX_Origin_Code,
RX_GPI,
RX_Generic_Paid_Indicator,
Rx_Chain_Pharmacy_ID,
Rx_Formulary_Drug_Indicator,
RX_Compound_Code,
RX_Copay_differential_amount,
Filler,
sourcefilename
)
select
split_part(records,'\t',1) as Account_Number,
split_part(records,'\t',2) as Claim_Number,
split_part(records,'\t',3) as Claim_Extention,
split_part(records,'\t',4) as Line_Number,
split_part(records,'\t',5) as Line_of_Business_Code,
split_part(records,'\t',6) as First_Date_of_Service,
split_part(records,'\t',7) as Paid_Date,
split_part(records,'\t',8) as Debit_Credit_Code,
split_part(records,'\t',9) as Member_Key,
split_part(records,'\t',10) as Disposition_Code,
split_part(records,'\t',11) as Group_Number,
split_part(records,'\t',12) as Section_Number,
split_part(records,'\t',13) as Subscriber_ID,
split_part(records,'\t',14) as Subscriber_SSN,
split_part(records,'\t',15) as Patient_DOB,
split_part(records,'\t',16) as Patient_SSN,
split_part(records,'\t',17) as Patient_Gender,
split_part(records,'\t',18) as Patient_Relationship,
split_part(records,'\t',19) as Patient_First_Name,
split_part(records,'\t',20) as Patient_Middle_Name,
split_part(records,'\t',21) as Patient_Last_Name,
split_part(records,'\t',22) as Patient_Zip_Code,
split_part(records,'\t',23) as Medicare_Primary_Indicator,
split_part(records,'\t',24) as Ineligible_Reason_Code_1,
split_part(records,'\t',25) as Ineligible_Reason_Code_2,
split_part(records,'\t',26) as Ineligible_Reason_Code_3,
split_part(records,'\t',27) as Last_Date_of_Service,
split_part(records,'\t',28) as Admission_Date,
split_part(records,'\t',29) as Discharge_Date,
split_part(records,'\t',30) as Received_Date,
split_part(records,'\t',31) as Claim_Reporting_Category,
split_part(records,'\t',32) as Policy_Type_Code,
split_part(records,'\t',33) as Claim_Origin_Code,
split_part(records,'\t',34) as CCP_Program_Indicator,
split_part(records,'\t',35) as CCP_Requirement_MET_code,
split_part(records,'\t',36) as Diagnosis_Classification_Code,
split_part(records,'\t',37) as Diagnosis_Category_Code,
split_part(records,'\t',38) as Diagnosis_Code_1,
split_part(records,'\t',39) as Diagnosis_Code_2,
split_part(records,'\t',40) as Diagnosis_Code_3,
split_part(records,'\t',41) as Diagnosis_Code_4,
split_part(records,'\t',42) as Diagnosis_Code_5,
split_part(records,'\t',43) as HCPCS_CPT_Code,
split_part(records,'\t',44) as Revenue_Code,
split_part(records,'\t',45) as ICD10_Indicator,
split_part(records,'\t',46) as ICD9_Procedure_Code_1,
split_part(records,'\t',47) as ICD9_Procedure_Code_2,
split_part(records,'\t',48) as ICD9_Procedure_Code_3,
split_part(records,'\t',49) as Place_of_Treatment,
split_part(records,'\t',50) as Type_of_Service,
split_part(records,'\t',51) as DRG,
split_part(records,'\t',52) as MDC,
split_part(records,'\t',53) as Patient_Status,
split_part(records,'\t',54) as Payment_Tier_Code,
split_part(records,'\t',55) as Services,
split_part(records,'\t',56) as Admission_Indicator,
split_part(records,'\t',57) as Day_Count,
split_part(records,'\t',58) as Visit_Indicator,
split_part(records,'\t',59) as Billed_Amount,
split_part(records,'\t',60) as Ineligible_Amount,
split_part(records,'\t',61) as Eligible_Amount,
split_part(records,'\t',62) as Deductible_Amount,
split_part(records,'\t',63) as Coinsurance_Amount,
split_part(records,'\t',64) as Copay_Amount,
split_part(records,'\t',65) as Paid_Amount,
split_part(records,'\t',66) as National_Access_Fee,
split_part(records,'\t',67) as Surcharge_Amount,
split_part(records,'\t',68) as IL_ADP_Discount,
split_part(records,'\t',69) as Allowed_Amount,
split_part(records,'\t',70) as Medicare_Paid_Amount,
split_part(records,'\t',71) as Workers_Compensation_Amount,
split_part(records,'\t',72) as All_Other_Payer_Amount,
split_part(records,'\t',73) as HCA_Draft_Amount,
split_part(records,'\t',74) as Claim_Filing_Code,
split_part(records,'\t',75) as Adjustment_Sequence_Number,
split_part(records,'\t',76) as Procedure_Code_Modifier,
split_part(records,'\t',77) as Payee_Code,
split_part(records,'\t',78) as Bill_Type_Class_Code,
split_part(records,'\t',79) as Bill_Frequency_Code,
split_part(records,'\t',80) as Bill_Institutional_Code,
split_part(records,'\t',81) as Provider_Network,
split_part(records,'\t',82) as Billing_Provider_Number,
split_part(records,'\t',83) as Billing_Provider_Tax_ID,
split_part(records,'\t',84) as Billing_National_Provider_Identifier,
split_part(records,'\t',85) as Billing_Provider_Name,
split_part(records,'\t',86) as Billing_Provider_Address_Line_1,
split_part(records,'\t',87) as Billing_Provider_Address_Line_2,
split_part(records,'\t',88) as Billing_Provider_City,
split_part(records,'\t',89) as Billing_Provider_State,
split_part(records,'\t',90) as Billing_Provider_Zip_Code,
split_part(records,'\t',91) as Performing_Provider_Number,
split_part(records,'\t',92) as Performing_Provider_Tax_ID,
split_part(records,'\t',93) as Performing_National_Provider_Identifier,
split_part(records,'\t',94) as Performing_Provider_Name,
split_part(records,'\t',95) as Performing_Provider_Specialty,
split_part(records,'\t',96) as Performing_Provider_Type_Code,
split_part(records,'\t',97) as Performing_Provider_Participation_Level,
split_part(records,'\t',98) as Performing_Provider_Address_Line_1,
split_part(records,'\t',99) as Performing_Provider_Address_Line_2,
split_part(records,'\t',100) as Performing_Provider_City,
split_part(records,'\t',101) as Performing_Provider_State,
split_part(records,'\t',102) as Performing_Provider_Zip_Code,
split_part(records,'\t',103) as Prescribing_Physician_First_Name,
split_part(records,'\t',104) as Prescribing_Physician_Last_Name,
split_part(records,'\t',105) as RX_ID,
split_part(records,'\t',106) as RX_National_Drug_Code,
split_part(records,'\t',107) as RX_Drug_Name,
split_part(records,'\t',108) as RX_Drug_Type_Code,
split_part(records,'\t',109) as RX_Drug_Category_Code,
split_part(records,'\t',110) as RX_Tier_Level_Code,
split_part(records,'\t',111) as RX_Therapeutic_Class,
split_part(records,'\t',112) as RX_DEA_Number,
split_part(records,'\t',113) as RX_Mail_Order_Indicator,
split_part(records,'\t',114) as RX_Dispense_as_Written,
split_part(records,'\t',115) as RX_Ingredient_Cost_Amount,
split_part(records,'\t',116) as RX_Dispensing_Fee_Amount,
split_part(records,'\t',117) as RX_Sales_Tax,
split_part(records,'\t',118) as RX_Metric_Quantity,
split_part(records,'\t',119) as RX_Days_Supply,
split_part(records,'\t',120) as RX_Origin_Code,
split_part(records,'\t',121) as RX_GPI,
split_part(records,'\t',122) as RX_Generic_Paid_Indicator,
split_part(records,'\t',123) as Rx_Chain_Pharmacy_ID,
split_part(records,'\t',124) as Rx_Formulary_Drug_Indicator,
split_part(records,'\t',125) as RX_Compound_Code,
split_part(records,'\t',126) as RX_Copay_differential_amount,
split_part(records,'\t',127) as Filler,
sourcefilename
from raw_tfk.rtemp_medical;

grant all on raw_tfk.raw_medical_enervest to public;

select top 100 * from raw_tfk.raw_medical_enervest;

select distinct account_number,line_of_business_code from raw_tfk.raw_medical_enervest