/* *********************** Import script of Traffk for RedShift ********************************* 
client name		:	Traffk
client id		:	
File Type		:	Pharmacy
Layout			:	Fixed Length
Create date		:	
Create by		:	Vijay Bahadur Kshetri	
****************************************************** */

--Temp Table
drop table if exists raw_tfk.temp_tfk_ethos_rx_20161124;
create table raw_tfk.temp_tfk_ethos_rx_20161124
(
	rowdata varchar(max)
);

copy raw_tfk.temp_tfk_ethos_rx_20161124
from 
's3://dasscrubinput/TFK/PA/stage0/tfk/tfk_eth/pharmacy/_!20161124/EthosEnergy_CDL6848_20161123.081622.txt'
credentials '********************************;aws_secret_access_key=***************************************' 
;


--Raw Table
drop table if exists raw_tfk.raw_tfk_ethos_rx_20161124;
create table raw_tfk.raw_tfk_ethos_rx_20161124
(
Record_Code  varchar(200),
Batch_Number  varchar(200),
Transaction_ID  varchar(200),
Transaction_ID_cross_reference  varchar(200),
Vendor_Batch_Code  varchar(200),
Vendor_Batch_Code_cross_reference  varchar(200),
Media_Type_Code  varchar(200),
Record_Type_Code  varchar(200),
NCPDP_Version_Number  varchar(200),
Transaction_Status  varchar(200),
Carrier_Number  varchar(200),
Contract_Number  varchar(200),
Group_Id  varchar(200),
Group_Pass_Thru  varchar(200),
Eligibility_Group_ID  varchar(200),
Claim_Submission_Type  varchar(200),
Plan_ID  varchar(200),
Insulin_Plan  varchar(200),
Specialty_Claim_Indicator  varchar(200),
DCRS_Super_ID  varchar(200),
Short_Cycle_Fill_Code  varchar(200),
Reserved_for_Future_Use_1  varchar(200),
Adjustment_Type  varchar(200),
Adjustment_Reason_Code  varchar(200),
Adjustment_Code  varchar(200),
Adjustment_Indicator  varchar(200),
Reversal_Status  varchar(200),
Paired_Adjustment_Sequence_Number  varchar(200),
Reserved_for_Future_Use_2  varchar(200),
Prescription_Service_Reference_Number  varchar(200),
MMRX_Rx_Number  varchar(200),
Fill_Number  varchar(200),
Fill_Number_Calculated  varchar(200),
Number_of_Refills_Authorized  varchar(200),
Dispense_As_Written  varchar(200),
Cutback_Indicator  varchar(200),
Dispensing_Status  varchar(200),
Date_Prescription_Written  varchar(200),
Direct_Claim_Payment_Release_Date  varchar(200),
Claim_Received_Date  varchar(200),
Time_Received  varchar(200),
Adjudication_Date  varchar(200),
Date_Of_Service  varchar(200),
Date_Of_Service_Julian  varchar(200),
Invoice_Date  varchar(200),
Prescription_Origin_Code  varchar(200),
Intermediary_Communication_Code  varchar(200),
Reject_Code_1  varchar(200),
Reject_Code_2  varchar(200),
Reject_Code_3  varchar(200),
Reject_Code_4  varchar(200),
Reject_Code_5  varchar(200),
Claim_Override_Code_1  varchar(200),
Claim_Override_Code_2  varchar(200),
Claim_Override_Code_3  varchar(200),
Reject_Override_Code  varchar(200),
Submission_Clarification_Code  varchar(200),
Communication_Type_Identifier  varchar(200),
Reserved_for_Future_Use_3  varchar(200),
Diagnosis_Code_Qualifier_1  varchar(200),
Diagnosis_Code_Qualifier_2  varchar(200),
Diagnosis_Code_Qualifier_3  varchar(200),
Diagnosis_Code_Qualifier_4  varchar(200),
Diagnosis_Code_Qualifier_5  varchar(200),
Diagnosis_Code_1  varchar(200),
Diagnosis_Code_2  varchar(200),
Diagnosis_Code_3  varchar(200),
Diagnosis_Code_4  varchar(200),
Diagnosis_Code_5  varchar(200),
Professional_Service_Code_1  varchar(200),
Professional_Service_Code_2  varchar(200),
Professional_Service_Code_3  varchar(200),
Professional_Service_Code_4  varchar(200),
Professional_Service_Code_5  varchar(200),
Professional_Service_Code_6  varchar(200),
Professional_Service_Code_7  varchar(200),
Professional_Service_Code_8  varchar(200),
Professional_Service_Code_9  varchar(200),
Reason_for_Service_Code_1  varchar(200),
Reason_for_Service_Code_2  varchar(200),
Reason_for_Service_Code_3  varchar(200),
Reason_for_Service_Code_4  varchar(200),
Reason_for_Service_Code_5  varchar(200),
Reason_for_Service_Code_6  varchar(200),
Reason_for_Service_Code_7  varchar(200),
Reason_for_Service_Code_8  varchar(200),
Reason_for_Service_Code_9  varchar(200),
Result_of_Service_Code_1  varchar(200),
Result_of_Service_Code_2  varchar(200),
Result_of_Service_Code_3  varchar(200),
Result_of_Service_Code_4  varchar(200),
Result_of_Service_Code_5  varchar(200),
Result_of_Service_Code_6  varchar(200),
Result_of_Service_Code_7  varchar(200),
Result_of_Service_Code_8  varchar(200),
Result_of_Service_Code_9  varchar(200),
Reserved_for_Future_Use_4  varchar(200),
Product_Service_ID_Qualifier  varchar(200),
Product_Service_ID  varchar(200),
Unit_Of_Measure  varchar(200),
Unit_Dose_Indicator  varchar(200),
Product_Service_Description  varchar(200),
Quantity_Intended_to_be_dispensed  varchar(200),
Quantity_Dispensed  varchar(200),
Prescribed_Days_Supply  varchar(200),
Days_Supply_Intended_to_be_dispensed  varchar(200),
Days_Supply  varchar(200),
Drug_Strength  varchar(200),
Dosage_Description  varchar(200),
GCN_Number  varchar(200),
Compound_Indicator  varchar(200),
Maintenance_Drug_Flag  varchar(200),
Drug_Indicator  varchar(200),
HCFA_Indicator  varchar(200),
Single_Source_Generic_Code  varchar(200),
Filler  varchar(200),
Therapeutic_Class_Code_Specific  varchar(200),
Therapeutic_ClassCode_AHFS  varchar(200),
Therapeutic_Class_Code_Generic  varchar(200),
Therapeutic_Class_Code_Standard  varchar(200),
USC_Code  varchar(200),
Generic_Product_Indicator  varchar(200),
Generic_Sequence_Number  varchar(200),
Route_of_Administration  varchar(200),
DEA_Class_of_Drug  varchar(200),
FDA_Drug_Efficacy_Indicator  varchar(200),
Drug_Class  varchar(200),
Drug_Category_Code  varchar(200),
Therapeutic_Chapter  varchar(200),
Client_Account_ID  varchar(200),
Cardholder_ID  varchar(200),
Cardholder_First_Name  varchar(200),
Cardholder_Middle_Name  varchar(200),
Cardholder_Last_Name  varchar(200),
Cardholder_Gender  varchar(200),
Cardholder_Date_of_Birth  varchar(200),
Cardholder_Address_1  varchar(200),
Cardholder_Address_2  varchar(200),
Cardholder_City  varchar(200),
Cardholder_State  varchar(200),
Cardholder_Zip_Code  varchar(200),
Coverage_Code  varchar(200),
Patient_Id_Qualifier  varchar(200),
Patient_Id  varchar(200),
Patient_First_Name  varchar(200),
Patient_Middle_Name  varchar(200),
Patient_Last_Name  varchar(200),
Patient_Gender  varchar(200),
Patient_Date_of_Birth  varchar(200),
Patient_Age  varchar(200),
Patient_Relationship_Code  varchar(200),
Person_Code  varchar(200),
Eligibility_Clarification_Code  varchar(200),
Eligibility_Relation_Code  varchar(200),
Patient_Location  varchar(200),
Reserved_for_Future_Use_5  varchar(200),
Prescriber_ID_Qualifier  varchar(200),
Prescriber_ID  varchar(200),
Prescriber_Last_Name  varchar(200),
Prescriber_Telephone_Number  varchar(200),
Service_Provider_ID_Qualifier  varchar(200),
Service_Provider_ID  varchar(200),
Pharmacy_Chain_ID  varchar(200),
Pharmacy_Name  varchar(200),
Pharmacy_Address  varchar(200),
Pharmacy_City  varchar(200),
Pharmacy_State  varchar(200),
Pharmacy_Zip  varchar(200),
Pharmacy_Phone_Number  varchar(200),
Pharmacy_Tax_ID_Number  varchar(200),
Pharmacy_County_Code  varchar(200),
Pharmacy_Class_Code  varchar(200),
Level_of_Service  varchar(200),
In_Network_Indicator  varchar(200),
Network_Type  varchar(200),
Pharmacy_NPI_Qualifier  varchar(200),
Pharmacy_NPI  varchar(200),
Reserved_for_Future_Use_6  varchar(200),
Basis_Of_Cost_Determination  varchar(200),
Administrative_Fee_Amount  varchar(200),
Admin_Effect_Indicator  varchar(200),
Usual_Customary  varchar(200),
Ingredient_Cost_Submitted  varchar(200),
Pharmacy_Submitted_Amount  varchar(200),
Ingredient_Cost  varchar(200),
Dispensing_Fee  varchar(200),
Incentive_Paid  varchar(200),
Professional_Fee  varchar(200),
Total_Sales_Tax  varchar(200),
Gross_Cost  varchar(200),
Client_Amount_Due  varchar(200),
Other_Payer_Amount_Paid  varchar(200),
Ingredient_Cost_Difference_Amount  varchar(200),
Additional_Patient_Discount_Applied  varchar(200),
Copay_Waiver_Amount  varchar(200),
Reserved_for_Future_Use_7  varchar(200),
Copay_Coinsurance  varchar(200),
Amount_Exceeding_Benefit_Maximum  varchar(200),
Deductible  varchar(200),
Amount_Attributed_to_Product_Selection  varchar(200),
Amount_Attributed_to_Sales_Tax  varchar(200),
Patient_Paid_Amount  varchar(200),
Excess_Copay_Amount  varchar(200),
Out_Of_Pocket_Apply_Amount  varchar(200),
Out_Of_Pocket_Remaining_Amount  varchar(200),
CAP_Apply_Amount  varchar(200),
CAP_Remaining_Amount  varchar(200),
Hold_Harmless_Code  varchar(200),
Hold_Harmless_Amount  varchar(200),
Member_Submit_Amount  varchar(200),
Deductible_Remaining_Amount  varchar(200),
Amount_Applied_to_Transitional_Assistance  varchar(200),
Reserved_for_Future_Use_8  varchar(200),
Percentage_Tax_Rate  varchar(200),
Percentage_Tax_Basis  varchar(200),
FUL_Unit_Price  varchar(200),
AGP_Unit_Price  varchar(200),
ACQ_Unit_Price  varchar(200),
AWP_Unit_Price  varchar(200),
MAC_Price  varchar(200),
Reserved_for_Future_Use_9  varchar(200),
Other_Coverage_Code  varchar(200),
COB_Primary_Claim_Type  varchar(200),
COB_Indicator  varchar(200),
Original_Claim_Received_Date  varchar(200),
Claim_Sequence_Number  varchar(200),
Claim_Direct_Indicator  varchar(200),
Check_Number  varchar(200),
Check_Date  varchar(200),
Formulary_Admin_Type  varchar(200),
Client_Formulary_Flag  varchar(200),
Formulary_Flag  varchar(200),
Copay_Modifier_ID  varchar(200),
Formulary_File_ID  varchar(200),
Preferred_Alternative_File_ID  varchar(200),
Copay_Product_Drug_List  varchar(200),
Copay_Product_Copay_Level  varchar(200),
Reserved_for_Future_Use_10  varchar(200),
Medicare_Recovery_Indicator  varchar(200),
Medicare_Indicator  varchar(200),
Prior_Authorization_Indicator  varchar(200),
Prior_Authorization_Number  varchar(200),
Prior_Authorization_Type_Code  varchar(200),
Claim_Reference_ID  varchar(200),
Memo_Item_Indicator  varchar(200),
Prior_Auth_Copay_Override_Indicator  varchar(200),
Patient_Level_Authorization_Indicator  varchar(200),
Reserved_for_Future_Use_11  varchar(200),
User_Sequence_Locator  varchar(200),
Insurance_Code  varchar(200),
Payroll_Class  varchar(200),
Client_Pass_Through  varchar(200),
Billable_Product_Service_ID_Qualifier  varchar(200),
Billable_Product_Service_ID  varchar(200),
Copay_Modifier_Indicator  varchar(200),
RRA_Penalty  varchar(200),
Enhanced_Prescription_Service_Reference_Number  varchar(200),
Amount_Attributed_to_Processor_Fee  varchar(200),
Amount_Attributed_to_Provider_Network_Selection  varchar(200),
Amount_Attributed_to_Product_Selection_Non_Preferred_Formulary_Selection  varchar(200),
Amount_Attributed_to_Product_Selection_Brand_Non_Preferred_Formulary_Selection  varchar(200),
Amount_Attributed_to_Coverage_Gap  varchar(200),
Health_Plan_funded_Assistance_Amount  varchar(200),
Coverage_Gap_Discount_Indicator  varchar(200),
Payment_Reference_Number  varchar(200),
Preferred_Pharmacy_Status_Code  varchar(200),
Reserved_for_Client_Specific_Customization  varchar(200),
sourcefilename varchar(200)
);
insert into raw_tfk.raw_tfk_ethos_rx_20161124
(
Record_Code,
Batch_Number,
Transaction_ID,
Transaction_ID_cross_reference,
Vendor_Batch_Code,
Vendor_Batch_Code_cross_reference,
Media_Type_Code,
Record_Type_Code,
NCPDP_Version_Number,
Transaction_Status,
Carrier_Number,
Contract_Number,
Group_Id,
Group_Pass_Thru,
Eligibility_Group_ID,
Claim_Submission_Type,
Plan_ID,
Insulin_Plan,
Specialty_Claim_Indicator,
DCRS_Super_ID,
Short_Cycle_Fill_Code,
Reserved_for_Future_Use_1,
Adjustment_Type,
Adjustment_Reason_Code,
Adjustment_Code,
Adjustment_Indicator,
Reversal_Status,
Paired_Adjustment_Sequence_Number,
Reserved_for_Future_Use_2,
Prescription_Service_Reference_Number,
MMRX_Rx_Number,
Fill_Number,
Fill_Number_Calculated,
Number_of_Refills_Authorized,
Dispense_As_Written,
Cutback_Indicator,
Dispensing_Status,
Date_Prescription_Written,
Direct_Claim_Payment_Release_Date,
Claim_Received_Date,
Time_Received,
Adjudication_Date,
Date_Of_Service,
Date_Of_Service_Julian,
Invoice_Date,
Prescription_Origin_Code,
Intermediary_Communication_Code,
Reject_Code_1,
Reject_Code_2,
Reject_Code_3,
Reject_Code_4,
Reject_Code_5,
Claim_Override_Code_1,
Claim_Override_Code_2,
Claim_Override_Code_3,
Reject_Override_Code,
Submission_Clarification_Code,
Communication_Type_Identifier,
Reserved_for_Future_Use_3,
Diagnosis_Code_Qualifier_1,
Diagnosis_Code_Qualifier_2,
Diagnosis_Code_Qualifier_3,
Diagnosis_Code_Qualifier_4,
Diagnosis_Code_Qualifier_5,
Diagnosis_Code_1,
Diagnosis_Code_2,
Diagnosis_Code_3,
Diagnosis_Code_4,
Diagnosis_Code_5,
Professional_Service_Code_1,
Professional_Service_Code_2,
Professional_Service_Code_3,
Professional_Service_Code_4,
Professional_Service_Code_5,
Professional_Service_Code_6,
Professional_Service_Code_7,
Professional_Service_Code_8,
Professional_Service_Code_9,
Reason_for_Service_Code_1,
Reason_for_Service_Code_2,
Reason_for_Service_Code_3,
Reason_for_Service_Code_4,
Reason_for_Service_Code_5,
Reason_for_Service_Code_6,
Reason_for_Service_Code_7,
Reason_for_Service_Code_8,
Reason_for_Service_Code_9,
Result_of_Service_Code_1,
Result_of_Service_Code_2,
Result_of_Service_Code_3,
Result_of_Service_Code_4,
Result_of_Service_Code_5,
Result_of_Service_Code_6,
Result_of_Service_Code_7,
Result_of_Service_Code_8,
Result_of_Service_Code_9,
Reserved_for_Future_Use_4,
Product_Service_ID_Qualifier,
Product_Service_ID,
Unit_Of_Measure,
Unit_Dose_Indicator,
Product_Service_Description,
Quantity_Intended_to_be_dispensed,
Quantity_Dispensed,
Prescribed_Days_Supply,
Days_Supply_Intended_to_be_dispensed,
Days_Supply,
Drug_Strength,
Dosage_Description,
GCN_Number,
Compound_Indicator,
Maintenance_Drug_Flag,
Drug_Indicator,
HCFA_Indicator,
Single_Source_Generic_Code,
Filler,
Therapeutic_Class_Code_Specific,
Therapeutic_ClassCode_AHFS,
Therapeutic_Class_Code_Generic,
Therapeutic_Class_Code_Standard,
USC_Code,
Generic_Product_Indicator,
Generic_Sequence_Number,
Route_of_Administration,
DEA_Class_of_Drug,
FDA_Drug_Efficacy_Indicator,
Drug_Class,
Drug_Category_Code,
Therapeutic_Chapter,
Client_Account_ID,
Cardholder_ID,
Cardholder_First_Name,
Cardholder_Middle_Name,
Cardholder_Last_Name,
Cardholder_Gender,
Cardholder_Date_of_Birth,
Cardholder_Address_1,
Cardholder_Address_2,
Cardholder_City,
Cardholder_State,
Cardholder_Zip_Code,
Coverage_Code,
Patient_Id_Qualifier,
Patient_Id,
Patient_First_Name,
Patient_Middle_Name,
Patient_Last_Name,
Patient_Gender,
Patient_Date_of_Birth,
Patient_Age,
Patient_Relationship_Code,
Person_Code,
Eligibility_Clarification_Code,
Eligibility_Relation_Code,
Patient_Location,
Reserved_for_Future_Use_5,
Prescriber_ID_Qualifier,
Prescriber_ID,
Prescriber_Last_Name,
Prescriber_Telephone_Number,
Service_Provider_ID_Qualifier,
Service_Provider_ID,
Pharmacy_Chain_ID,
Pharmacy_Name,
Pharmacy_Address,
Pharmacy_City,
Pharmacy_State,
Pharmacy_Zip,
Pharmacy_Phone_Number,
Pharmacy_Tax_ID_Number,
Pharmacy_County_Code,
Pharmacy_Class_Code,
Level_of_Service,
In_Network_Indicator,
Network_Type,
Pharmacy_NPI_Qualifier,
Pharmacy_NPI,
Reserved_for_Future_Use_6,
Basis_Of_Cost_Determination,
Administrative_Fee_Amount,
Admin_Effect_Indicator,
Usual_Customary,
Ingredient_Cost_Submitted,
Pharmacy_Submitted_Amount,
Ingredient_Cost,
Dispensing_Fee,
Incentive_Paid,
Professional_Fee,
Total_Sales_Tax,
Gross_Cost,
Client_Amount_Due,
Other_Payer_Amount_Paid,
Ingredient_Cost_Difference_Amount,
Additional_Patient_Discount_Applied,
Copay_Waiver_Amount,
Reserved_for_Future_Use_7,
Copay_Coinsurance,
Amount_Exceeding_Benefit_Maximum,
Deductible,
Amount_Attributed_to_Product_Selection,
Amount_Attributed_to_Sales_Tax,
Patient_Paid_Amount,
Excess_Copay_Amount,
Out_Of_Pocket_Apply_Amount,
Out_Of_Pocket_Remaining_Amount,
CAP_Apply_Amount,
CAP_Remaining_Amount,
Hold_Harmless_Code,
Hold_Harmless_Amount,
Member_Submit_Amount,
Deductible_Remaining_Amount,
Amount_Applied_to_Transitional_Assistance,
Reserved_for_Future_Use_8,
Percentage_Tax_Rate,
Percentage_Tax_Basis,
FUL_Unit_Price,
AGP_Unit_Price,
ACQ_Unit_Price,
AWP_Unit_Price,
MAC_Price,
Reserved_for_Future_Use_9,
Other_Coverage_Code,
COB_Primary_Claim_Type,
COB_Indicator,
Original_Claim_Received_Date,
Claim_Sequence_Number,
Claim_Direct_Indicator,
Check_Number,
Check_Date,
Formulary_Admin_Type,
Client_Formulary_Flag,
Formulary_Flag,
Copay_Modifier_ID,
Formulary_File_ID,
Preferred_Alternative_File_ID,
Copay_Product_Drug_List,
Copay_Product_Copay_Level,
Reserved_for_Future_Use_10,
Medicare_Recovery_Indicator,
Medicare_Indicator,
Prior_Authorization_Indicator,
Prior_Authorization_Number,
Prior_Authorization_Type_Code,
Claim_Reference_ID,
Memo_Item_Indicator,
Prior_Auth_Copay_Override_Indicator,
Patient_Level_Authorization_Indicator,
Reserved_for_Future_Use_11,
User_Sequence_Locator,
Insurance_Code,
Payroll_Class,
Client_Pass_Through,
Billable_Product_Service_ID_Qualifier,
Billable_Product_Service_ID,
Copay_Modifier_Indicator,
RRA_Penalty,
Enhanced_Prescription_Service_Reference_Number,
Amount_Attributed_to_Processor_Fee,
Amount_Attributed_to_Provider_Network_Selection,
Amount_Attributed_to_Product_Selection_Non_Preferred_Formulary_Selection,
Amount_Attributed_to_Product_Selection_Brand_Non_Preferred_Formulary_Selection,
Amount_Attributed_to_Coverage_Gap,
Health_Plan_funded_Assistance_Amount,
Coverage_Gap_Discount_Indicator,
Payment_Reference_Number,
Preferred_Pharmacy_Status_Code,
Reserved_for_Client_Specific_Customization,
sourcefilename
)
select
trim(substring(rowdata,1,1)) as Record_Code,
trim(substring(rowdata,2,5)) as Batch_Number,
trim(substring(rowdata,7,18)) as Transaction_ID,
trim(substring(rowdata,25,18)) as Transaction_ID_cross_reference,
trim(substring(rowdata,43,14)) as Vendor_Batch_Code,
trim(substring(rowdata,57,14)) as Vendor_Batch_Code_cross_reference,
trim(substring(rowdata,71,1)) as Media_Type_Code,
trim(substring(rowdata,72,1)) as Record_Type_Code,
trim(substring(rowdata,73,2)) as NCPDP_Version_Number,
trim(substring(rowdata,75,2)) as Transaction_Status,
trim(substring(rowdata,77,8)) as Carrier_Number,
trim(substring(rowdata,85,8)) as Contract_Number,
trim(substring(rowdata,93,15)) as Group_Id,
trim(substring(rowdata,108,30)) as Group_Pass_Thru,
trim(substring(rowdata,138,15)) as Eligibility_Group_ID,
trim(substring(rowdata,153,1)) as Claim_Submission_Type,
trim(substring(rowdata,154,8)) as Plan_ID,
trim(substring(rowdata,162,1)) as Insulin_Plan,
trim(substring(rowdata,163,1)) as Specialty_Claim_Indicator,
trim(substring(rowdata,164,10)) as DCRS_Super_ID,
trim(substring(rowdata,174,1)) as Short_Cycle_Fill_Code,
trim(substring(rowdata,175,8)) as Reserved_for_Future_Use_1,
trim(substring(rowdata,183,1)) as Adjustment_Type,
trim(substring(rowdata,184,3)) as Adjustment_Reason_Code,
trim(substring(rowdata,187,2)) as Adjustment_Code,
trim(substring(rowdata,189,1)) as Adjustment_Indicator,
trim(substring(rowdata,190,1)) as Reversal_Status,
trim(substring(rowdata,191,10)) as Paired_Adjustment_Sequence_Number,
trim(substring(rowdata,201,14)) as Reserved_for_Future_Use_2,
trim(substring(rowdata,215,9)) as Prescription_Service_Reference_Number,
trim(substring(rowdata,224,10)) as MMRX_Rx_Number,
trim(substring(rowdata,234,2)) as Fill_Number,
trim(substring(rowdata,236,2)) as Fill_Number_Calculated,
trim(substring(rowdata,238,2)) as Number_of_Refills_Authorized,
trim(substring(rowdata,240,1)) as Dispense_As_Written,
trim(substring(rowdata,241,1)) as Cutback_Indicator,
trim(substring(rowdata,242,1)) as Dispensing_Status,
trim(substring(rowdata,243,8)) as Date_Prescription_Written,
trim(substring(rowdata,251,8)) as Direct_Claim_Payment_Release_Date,
trim(substring(rowdata,259,8)) as Claim_Received_Date,
trim(substring(rowdata,267,8)) as Time_Received,
trim(substring(rowdata,275,8)) as Adjudication_Date,
trim(substring(rowdata,283,8)) as Date_Of_Service,
trim(substring(rowdata,291,10)) as Date_Of_Service_Julian,
trim(substring(rowdata,301,8)) as Invoice_Date,
trim(substring(rowdata,309,1)) as Prescription_Origin_Code,
trim(substring(rowdata,310,2)) as Intermediary_Communication_Code,
trim(substring(rowdata,312,3)) as Reject_Code_1,
trim(substring(rowdata,315,3)) as Reject_Code_2,
trim(substring(rowdata,318,3)) as Reject_Code_3,
trim(substring(rowdata,321,3)) as Reject_Code_4,
trim(substring(rowdata,324,3)) as Reject_Code_5,
trim(substring(rowdata,327,2)) as Claim_Override_Code_1,
trim(substring(rowdata,329,2)) as Claim_Override_Code_2,
trim(substring(rowdata,331,2)) as Claim_Override_Code_3,
trim(substring(rowdata,333,1)) as Reject_Override_Code,
trim(substring(rowdata,334,2)) as Submission_Clarification_Code,
trim(substring(rowdata,336,2)) as Communication_Type_Identifier,
trim(substring(rowdata,338,20)) as Reserved_for_Future_Use_3,
trim(substring(rowdata,358,2)) as Diagnosis_Code_Qualifier_1,
trim(substring(rowdata,360,2)) as Diagnosis_Code_Qualifier_2,
trim(substring(rowdata,362,2)) as Diagnosis_Code_Qualifier_3,
trim(substring(rowdata,364,2)) as Diagnosis_Code_Qualifier_4,
trim(substring(rowdata,366,2)) as Diagnosis_Code_Qualifier_5,
trim(substring(rowdata,368,15)) as Diagnosis_Code_1,
trim(substring(rowdata,383,15)) as Diagnosis_Code_2,
trim(substring(rowdata,398,15)) as Diagnosis_Code_3,
trim(substring(rowdata,413,15)) as Diagnosis_Code_4,
trim(substring(rowdata,428,15)) as Diagnosis_Code_5,
trim(substring(rowdata,443,2)) as Professional_Service_Code_1,
trim(substring(rowdata,445,2)) as Professional_Service_Code_2,
trim(substring(rowdata,447,2)) as Professional_Service_Code_3,
trim(substring(rowdata,449,2)) as Professional_Service_Code_4,
trim(substring(rowdata,451,2)) as Professional_Service_Code_5,
trim(substring(rowdata,453,2)) as Professional_Service_Code_6,
trim(substring(rowdata,455,2)) as Professional_Service_Code_7,
trim(substring(rowdata,457,2)) as Professional_Service_Code_8,
trim(substring(rowdata,459,2)) as Professional_Service_Code_9,
trim(substring(rowdata,461,2)) as Reason_for_Service_Code_1,
trim(substring(rowdata,463,2)) as Reason_for_Service_Code_2,
trim(substring(rowdata,465,2)) as Reason_for_Service_Code_3,
trim(substring(rowdata,467,2)) as Reason_for_Service_Code_4,
trim(substring(rowdata,469,2)) as Reason_for_Service_Code_5,
trim(substring(rowdata,471,2)) as Reason_for_Service_Code_6,
trim(substring(rowdata,473,2)) as Reason_for_Service_Code_7,
trim(substring(rowdata,475,2)) as Reason_for_Service_Code_8,
trim(substring(rowdata,477,2)) as Reason_for_Service_Code_9,
trim(substring(rowdata,479,2)) as Result_of_Service_Code_1,
trim(substring(rowdata,481,2)) as Result_of_Service_Code_2,
trim(substring(rowdata,483,2)) as Result_of_Service_Code_3,
trim(substring(rowdata,485,2)) as Result_of_Service_Code_4,
trim(substring(rowdata,487,2)) as Result_of_Service_Code_5,
trim(substring(rowdata,489,2)) as Result_of_Service_Code_6,
trim(substring(rowdata,491,2)) as Result_of_Service_Code_7,
trim(substring(rowdata,493,2)) as Result_of_Service_Code_8,
trim(substring(rowdata,495,2)) as Result_of_Service_Code_9,
trim(substring(rowdata,497,20)) as Reserved_for_Future_Use_4,
trim(substring(rowdata,517,2)) as Product_Service_ID_Qualifier,
trim(substring(rowdata,519,19)) as Product_Service_ID,
trim(substring(rowdata,538,2)) as Unit_Of_Measure,
trim(substring(rowdata,540,1)) as Unit_Dose_Indicator,
trim(substring(rowdata,541,30)) as Product_Service_Description,
trim(substring(rowdata,571,10)) as Quantity_Intended_to_be_dispensed,
trim(substring(rowdata,581,10)) as Quantity_Dispensed,
trim(substring(rowdata,591,3)) as Prescribed_Days_Supply,
trim(substring(rowdata,594,3)) as Days_Supply_Intended_to_be_dispensed,
trim(substring(rowdata,597,3)) as Days_Supply,
trim(substring(rowdata,600,10)) as Drug_Strength,
trim(substring(rowdata,610,2)) as Dosage_Description,
trim(substring(rowdata,612,6)) as GCN_Number,
trim(substring(rowdata,618,1)) as Compound_Indicator,
trim(substring(rowdata,619,1)) as Maintenance_Drug_Flag,
trim(substring(rowdata,620,1)) as Drug_Indicator,
trim(substring(rowdata,621,1)) as HCFA_Indicator,
trim(substring(rowdata,622,2)) as Single_Source_Generic_Code,
trim(substring(rowdata,624,3)) as Filler,
trim(substring(rowdata,627,3)) as Therapeutic_Class_Code_Specific,
trim(substring(rowdata,630,6)) as Therapeutic_ClassCode_AHFS,
trim(substring(rowdata,636,2)) as Therapeutic_Class_Code_Generic,
trim(substring(rowdata,638,2)) as Therapeutic_Class_Code_Standard,
trim(substring(rowdata,640,5)) as USC_Code,
trim(substring(rowdata,645,1)) as Generic_Product_Indicator,
trim(substring(rowdata,646,6)) as Generic_Sequence_Number,
trim(substring(rowdata,652,1)) as Route_of_Administration,
trim(substring(rowdata,653,1)) as DEA_Class_of_Drug,
trim(substring(rowdata,654,1)) as FDA_Drug_Efficacy_Indicator,
trim(substring(rowdata,655,1)) as Drug_Class,
trim(substring(rowdata,656,1)) as Drug_Category_Code,
trim(substring(rowdata,657,8)) as Therapeutic_Chapter,
trim(substring(rowdata,665,12)) as Client_Account_ID,
trim(substring(rowdata,677,20)) as Cardholder_ID,
trim(substring(rowdata,697,25)) as Cardholder_First_Name,
trim(substring(rowdata,722,25)) as Cardholder_Middle_Name,
trim(substring(rowdata,747,35)) as Cardholder_Last_Name,
trim(substring(rowdata,782,1)) as Cardholder_Gender,
trim(substring(rowdata,783,8)) as Cardholder_Date_of_Birth,
trim(substring(rowdata,791,55)) as Cardholder_Address_1,
trim(substring(rowdata,846,55)) as Cardholder_Address_2,
trim(substring(rowdata,901,30)) as Cardholder_City,
trim(substring(rowdata,931,2)) as Cardholder_State,
trim(substring(rowdata,933,15)) as Cardholder_Zip_Code,
trim(substring(rowdata,948,1)) as Coverage_Code,
trim(substring(rowdata,949,2)) as Patient_Id_Qualifier,
trim(substring(rowdata,951,20)) as Patient_Id,
trim(substring(rowdata,971,25)) as Patient_First_Name,
trim(substring(rowdata,996,25)) as Patient_Middle_Name,
trim(substring(rowdata,1021,35)) as Patient_Last_Name,
trim(substring(rowdata,1056,1)) as Patient_Gender,
trim(substring(rowdata,1057,8)) as Patient_Date_of_Birth,
trim(substring(rowdata,1065,3)) as Patient_Age,
trim(substring(rowdata,1068,1)) as Patient_Relationship_Code,
trim(substring(rowdata,1069,3)) as Person_Code,
trim(substring(rowdata,1072,2)) as Eligibility_Clarification_Code,
trim(substring(rowdata,1074,1)) as Eligibility_Relation_Code,
trim(substring(rowdata,1075,2)) as Patient_Location,
trim(substring(rowdata,1077,20)) as Reserved_for_Future_Use_5,
trim(substring(rowdata,1097,2)) as Prescriber_ID_Qualifier,
trim(substring(rowdata,1099,15)) as Prescriber_ID,
trim(substring(rowdata,1114,15)) as Prescriber_Last_Name,
trim(substring(rowdata,1129,10)) as Prescriber_Telephone_Number,
trim(substring(rowdata,1139,2)) as Service_Provider_ID_Qualifier,
trim(substring(rowdata,1141,10)) as Service_Provider_ID,
trim(substring(rowdata,1151,4)) as Pharmacy_Chain_ID,
trim(substring(rowdata,1155,35)) as Pharmacy_Name,
trim(substring(rowdata,1190,55)) as Pharmacy_Address,
trim(substring(rowdata,1245,30)) as Pharmacy_City,
trim(substring(rowdata,1275,2)) as Pharmacy_State,
trim(substring(rowdata,1277,15)) as Pharmacy_Zip,
trim(substring(rowdata,1292,10)) as Pharmacy_Phone_Number,
trim(substring(rowdata,1302,9)) as Pharmacy_Tax_ID_Number,
trim(substring(rowdata,1311,3)) as Pharmacy_County_Code,
trim(substring(rowdata,1314,1)) as Pharmacy_Class_Code,
trim(substring(rowdata,1315,2)) as Level_of_Service,
trim(substring(rowdata,1317,1)) as In_Network_Indicator,
trim(substring(rowdata,1318,1)) as Network_Type,
trim(substring(rowdata,1319,2)) as Pharmacy_NPI_Qualifier,
trim(substring(rowdata,1321,10)) as Pharmacy_NPI,
trim(substring(rowdata,1331,8)) as Reserved_for_Future_Use_6,
trim(substring(rowdata,1339,2)) as Basis_Of_Cost_Determination,
trim(substring(rowdata,1341,8)) as Administrative_Fee_Amount,
trim(substring(rowdata,1349,1)) as Admin_Effect_Indicator,
trim(substring(rowdata,1350,8)) as Usual_Customary,
trim(substring(rowdata,1358,8)) as Ingredient_Cost_Submitted,
trim(substring(rowdata,1366,8)) as Pharmacy_Submitted_Amount,
trim(substring(rowdata,1374,8)) as Ingredient_Cost,
trim(substring(rowdata,1382,8)) as Dispensing_Fee,
trim(substring(rowdata,1390,8)) as Incentive_Paid,
trim(substring(rowdata,1398,8)) as Professional_Fee,
trim(substring(rowdata,1406,8)) as Total_Sales_Tax,
trim(substring(rowdata,1414,8)) as Gross_Cost,
trim(substring(rowdata,1422,8)) as Client_Amount_Due,
trim(substring(rowdata,1430,8)) as Other_Payer_Amount_Paid,
trim(substring(rowdata,1438,8)) as Ingredient_Cost_Difference_Amount,
trim(substring(rowdata,1446,8)) as Additional_Patient_Discount_Applied,
trim(substring(rowdata,1454,8)) as Copay_Waiver_Amount,
trim(substring(rowdata,1462,4)) as Reserved_for_Future_Use_7,
trim(substring(rowdata,1466,8)) as Copay_Coinsurance,
trim(substring(rowdata,1474,8)) as Amount_Exceeding_Benefit_Maximum,
trim(substring(rowdata,1482,8)) as Deductible,
trim(substring(rowdata,1490,8)) as Amount_Attributed_to_Product_Selection,
trim(substring(rowdata,1498,8)) as Amount_Attributed_to_Sales_Tax,
trim(substring(rowdata,1506,8)) as Patient_Paid_Amount,
trim(substring(rowdata,1514,8)) as Excess_Copay_Amount,
trim(substring(rowdata,1522,8)) as Out_Of_Pocket_Apply_Amount,
trim(substring(rowdata,1530,10)) as Out_Of_Pocket_Remaining_Amount,
trim(substring(rowdata,1540,8)) as CAP_Apply_Amount,
trim(substring(rowdata,1548,10)) as CAP_Remaining_Amount,
trim(substring(rowdata,1558,1)) as Hold_Harmless_Code,
trim(substring(rowdata,1559,8)) as Hold_Harmless_Amount,
trim(substring(rowdata,1567,8)) as Member_Submit_Amount,
trim(substring(rowdata,1575,10)) as Deductible_Remaining_Amount,
trim(substring(rowdata,1585,8)) as Amount_Applied_to_Transitional_Assistance,
trim(substring(rowdata,1593,2)) as Reserved_for_Future_Use_8,
trim(substring(rowdata,1595,7)) as Percentage_Tax_Rate,
trim(substring(rowdata,1602,2)) as Percentage_Tax_Basis,
trim(substring(rowdata,1604,11)) as FUL_Unit_Price,
trim(substring(rowdata,1615,11)) as AGP_Unit_Price,
trim(substring(rowdata,1626,11)) as ACQ_Unit_Price,
trim(substring(rowdata,1637,11)) as AWP_Unit_Price,
trim(substring(rowdata,1648,11)) as MAC_Price,
trim(substring(rowdata,1659,20)) as Reserved_for_Future_Use_9,
trim(substring(rowdata,1679,2)) as Other_Coverage_Code,
trim(substring(rowdata,1681,1)) as COB_Primary_Claim_Type,
trim(substring(rowdata,1682,1)) as COB_Indicator,
trim(substring(rowdata,1683,8)) as Original_Claim_Received_Date,
trim(substring(rowdata,1691,5)) as Claim_Sequence_Number,
trim(substring(rowdata,1696,1)) as Claim_Direct_Indicator,
trim(substring(rowdata,1697,7)) as Check_Number,
trim(substring(rowdata,1704,8)) as Check_Date,
trim(substring(rowdata,1712,1)) as Formulary_Admin_Type,
trim(substring(rowdata,1713,1)) as Client_Formulary_Flag,
trim(substring(rowdata,1714,1)) as Formulary_Flag,
trim(substring(rowdata,1715,10)) as Copay_Modifier_ID,
trim(substring(rowdata,1725,10)) as Formulary_File_ID,
trim(substring(rowdata,1735,10)) as Preferred_Alternative_File_ID,
trim(substring(rowdata,1745,5)) as Copay_Product_Drug_List,
trim(substring(rowdata,1750,5)) as Copay_Product_Copay_Level,
trim(substring(rowdata,1755,10)) as Reserved_for_Future_Use_10,
trim(substring(rowdata,1765,1)) as Medicare_Recovery_Indicator,
trim(substring(rowdata,1766,1)) as Medicare_Indicator,
trim(substring(rowdata,1767,1)) as Prior_Authorization_Indicator,
trim(substring(rowdata,1768,11)) as Prior_Authorization_Number,
trim(substring(rowdata,1779,2)) as Prior_Authorization_Type_Code,
trim(substring(rowdata,1781,30)) as Claim_Reference_ID,
trim(substring(rowdata,1811,1)) as Memo_Item_Indicator,
trim(substring(rowdata,1812,1)) as Prior_Auth_Copay_Override_Indicator,
trim(substring(rowdata,1813,1)) as Patient_Level_Authorization_Indicator,
trim(substring(rowdata,1814,18)) as Reserved_for_Future_Use_11,
trim(substring(rowdata,1832,20)) as User_Sequence_Locator,
trim(substring(rowdata,1852,20)) as Insurance_Code,
trim(substring(rowdata,1872,1)) as Payroll_Class,
trim(substring(rowdata,1873,200)) as Client_Pass_Through,
trim(substring(rowdata,2073,2)) as Billable_Product_Service_ID_Qualifier,
trim(substring(rowdata,2075,19)) as Billable_Product_Service_ID,
trim(substring(rowdata,2094,1)) as Copay_Modifier_Indicator,
trim(substring(rowdata,2095,8)) as RRA_Penalty,
trim(substring(rowdata,2103,12)) as Enhanced_Prescription_Service_Reference_Number,
trim(substring(rowdata,2115,8)) as Amount_Attributed_to_Processor_Fee,
trim(substring(rowdata,2123,8)) as Amount_Attributed_to_Provider_Network_Selection,
trim(substring(rowdata,2131,8)) as Amount_Attributed_to_Product_Selection_Non_Preferred_Formulary_Selection,
trim(substring(rowdata,2139,8)) as Amount_Attributed_to_Product_Selection_Brand_Non_Preferred_Formulary_Selection,
trim(substring(rowdata,2147,8)) as Amount_Attributed_to_Coverage_Gap,
trim(substring(rowdata,2155,8)) as Health_Plan_funded_Assistance_Amount,
trim(substring(rowdata,2163,1)) as Coverage_Gap_Discount_Indicator,
trim(substring(rowdata,2164,30)) as Payment_Reference_Number,
trim(substring(rowdata,2194,1)) as Preferred_Pharmacy_Status_Code,
trim(substring(rowdata,2195,106)) as Reserved_for_Client_Specific_Customization,
'EthosEnergy_CDL6848_20161123.081622.txt' as sourcefilename
from raw_tfk.temp_tfk_ethos_rx_20161124;

select * from raw_tfk.raw_tfk_ethos_rx_20161124 limit 10;