/* *********************** Import script of Traffk for RedShift ********************************* 
client name		:	Traffk
client id		:	
File Type		:	Medical
Layout			:	Delimiter '\t'
Create date		:	
Create by		:	Vijay Bahadur Kshetri	
****************************************************** */
--Temp Table
drop table if exists raw_tfk.temp_tfk_ethos_med_20161118;
create table raw_tfk.temp_tfk_ethos_med_20161118
(
	rowdata varchar(max)
);

copy raw_tfk.temp_tfk_ethos_med_20161118
from 
's3://dasscrubinput/TFK/PA/stage0/tfk/tfk_eth/medical/20161118/90932834-UMED_CLMDATA___20161001_20161031.txt'
credentials 'aws_access_key_id=*********************************;aws_secret_access_key=***********************************' 
delimiter '~';

--Rstag Table
drop table if exists raw_tfk.rstag_tfk_ethos_med_20161118;
create table raw_tfk.rstag_tfk_ethos_med_20161118
(
ps_unique_id  varchar (200),
customer_nbr  varchar (200),
group_nbr  varchar (200),
Filler  varchar (200),
subgroup_nbr  varchar (200),
account_nbr  varchar (200),
file_id  varchar (200),
AdjustmentCode  varchar (200),
PreferredvsNonPreferredBenefitLevel  varchar (200),
GeneralCategoryofHealthPlan  varchar (200),
LineofBusiness  varchar (200),
ClassificationCode  varchar (200),
BenefitIdentificationCode_BIC  varchar (200),
PlanCodeorExtensionofHierarchy  varchar (200),
BenefitTier  varchar (200),
FundingArrangement  varchar (200),
EmployeeSSN  varchar (200),
EmployeeLastName  varchar (200),
EmployeeFirstNameorInitial  varchar (200),
EmployeeGender  varchar (200),
EmployeeDateofBirth  varchar (200),
EmployeeZipCode  varchar (200),
EmployeeState  varchar (200),
CoverageEnrollmentTier  varchar (200),
MemberSSN  varchar (200),
MemberID_AssignedinDataWarehouse  varchar (200),
MemberNumber  varchar (200),
MemberLastName  varchar (200),
MemberFirstName  varchar (200),
MemberGender  varchar (200),
MemberRelationshiptoEmployee  varchar (200),
MemberDateofBirth  varchar (200),
Source_SpecificTransactionIDNumber  varchar (200),
ACASGenerationSegmentNumber  varchar (200),
ACASPointerBacktoPreviousGenSeg  varchar (200),
TraditionalClaimID  varchar (200),
ExpensePayLineNumber  varchar (200),
ClaimLineID_AssignedinDataWarehouse  varchar (200),
EmployeeNetworkID  varchar (200),
ServicingProviderNetworkID  varchar (200),
ReferralType  varchar (200),
PCPsIRSTaxIdentificationNumber_TINFormatCode  varchar (200),
PCPsIRSTaxIdentificationNumber_TIN  varchar (200),
PCPsName_LastorFull  varchar (200),
ServicingProviderTaxIDNumber_TINFormatCode  varchar (200),
ServicingProviderTaxIDNumber_TIN  varchar (200),
ServicingProviderPIN  varchar (200),
ServicingProviderName_LastorFull  varchar (200),
ServicingProviderStreetAddress1  varchar (200),
ServicingProviderStreetAddress2  varchar (200),
ServicingProviderCity  varchar (200),
ServicingProviderState  varchar (200),
ServicingProviderZipCode  varchar (200),
ServicingProviderType  varchar (200),
ServicingProviderSpecialtyCode  varchar (200),
AssignmentofBenefitstoProviderCode  varchar (200),
ParticipatingProviderCode  varchar (200),
DateClaimSubmissionReceived  varchar (200),
DateProcessed_Non_HMOOnly  varchar (200),
DateServiceStarted  varchar (200),
DateServiceStopped  varchar (200),
DateProcessed_All  varchar (200),
Filler1  varchar (200),
Filler2  varchar (200),
Filler3  varchar (200),
MajorDiagnosticCategory_MDC  varchar (200),
DiagnosisRelatedGroup_DRG  varchar (200),
LineLevelProcedureCode  varchar (200),
Line_LevelProcedureCodeModifier  varchar (200),
Line_LevelProcedureCodeType  varchar (200),
Filler4  varchar (200),
Filler5  varchar (200),
Filler6  varchar (200),
TypeofService  varchar (200),
ServiceBenefitCode  varchar (200),
ToothNumber  varchar (200),
PlaceofService  varchar (200),
UB92PatientDischargeStatus  varchar (200),
UB92RevenueCenter  varchar (200),
UB92BillType  varchar (200),
NumberUnitsofService  varchar (200),
SourceNumberUnitsofService  varchar (200),
GrossSubmittedExpense  varchar (200),
NetSubmittedExpense  varchar (200),
NotCoveredAmount1  varchar (200),
NotCoveredAmount2  varchar (200),
NotCoveredAmount3  varchar (200),
ActionorReasonCode1  varchar (200),
ActionorReasonCode2  varchar (200),
ActionorReasonCode3  varchar (200),
CoveredExpense  varchar (200),
AllowedAmount  varchar (200),
Filler7  varchar (200),
CopaymentAmount  varchar (200),
SourceCopaymentAmount  varchar (200),
DeductibleAmount  varchar (200),
Coinsurance  varchar (200),
SourceCoinsuranceAmount  varchar (200),
BenefitPayable  varchar (200),
PaidAmount  varchar (200),
COBPaidAmount  varchar (200),
AetnaHealthFundBeforeFundDeductible  varchar (200),
AetnaHealthFundPayableAmount  varchar (200),
Savings_NegotiatedFee  varchar (200),
SavingsR_and_C  varchar (200),
SavingsCOB  varchar (200),
SavingsSourceCOB  varchar (200),
MedicareCode  varchar (200),
TypeofExpenseCOB  varchar (200),
COBCode  varchar (200),
NationalDrugCode  varchar (200),
MemberCUMBID  varchar (200),
StatusofClaim  varchar (200),
Non_SSNEmployeeID  varchar (200),
ReversalCode  varchar (200),
AdmitCounter  varchar (200),
AdministrativeSavingsAmount  varchar (200),
AexcelProviderDesignationCode  varchar (200),
AexcelPlanDesignCode  varchar (200),
AexcelBenefitTierCode  varchar (200),
AexcelDesignatedProviderSpecialty  varchar (200),
ProductDistinctionCode  varchar (200),
BilledEligibleAmount_masked_donotusethisfield  varchar (200),
ServicingProviderClassCode  varchar (200),
PresentonAdmissionCode_1  varchar (200),
PresentonAdmissionCode_2  varchar (200),
PresentonAdmissionCode_3  varchar (200),
Filler8  varchar (200),
Filler9  varchar (200),
Filler10  varchar (200),
PricingMethodCode  varchar (200),
ServicingProviderTypeClassCode  varchar (200),
ServicingProviderSpecialtyCategoryCode  varchar (200),
ServicingProviderNPI  varchar (200),
TotalDeductibleMetIndicator  varchar (200),
TotalInterestAmount  varchar (200),
TotalSurchargeAmount  varchar (200),
Filler11  varchar (200),
HCFAPlaceofServiceCode  varchar (200),
HCFAAdmitSourceCode  varchar (200),
HCFAAdmitTypeCode  varchar (200),
AdmissionDate  varchar (200),
DischargeDate  varchar (200),
Line_LevelProcedureCodeModifier_2  varchar (200),
Line_LevelProcedureCodeModifier_3  varchar (200),
PresentonAdmissionCode_4  varchar (200),
PresentonAdmissionCode_5  varchar (200),
PresentonAdmissionCode_6  varchar (200),
PresentonAdmissionCode_7  varchar (200),
PresentonAdmissionCode_8  varchar (200),
PresentonAdmissionCode_9  varchar (200),
PresentonAdmissionCode_10  varchar (200),
DiagnosisCode1  varchar (200),
DiagnosisCode2  varchar (200),
DiagnosisCode3  varchar (200),
DiagnosisCode4  varchar (200),
DiagnosisCode5  varchar (200),
DiagnosisCode6  varchar (200),
DiagnosisCode7  varchar (200),
DiagnosisCode8  varchar (200),
DiagnosisCode9  varchar (200),
DiagnosisCode10  varchar (200),
ICDProcedureCode1  varchar (200),
ICDProcedureCode2  varchar (200),
ICDProcedureCode3  varchar (200),
ICDProcedureCode4  varchar (200),
ICDProcedureCode5  varchar (200),
ICDProcedureCode6  varchar (200),
AetnaHealthFundDeterminationOrderCode  varchar (200),
AetnaHealthFundMemberShareofCoinsuranceAmount  varchar (200),
AetnaHealthFundMemberCopayAmount  varchar (200),
AetnaHealthFundMemberDeductibleAmount  varchar (200),
Filler12  varchar (200),
Filler13  varchar (200),
ICD10Indicator  varchar (200),
ExchangeID  varchar (200),
Filler14  varchar (200),
EndofRecordMarker  varchar (200),
sourcefilename varchar(200)
);
insert into raw_tfk.rstag_tfk_ethos_med_20161118
(
ps_unique_id,
customer_nbr,
group_nbr,
Filler,
subgroup_nbr,
account_nbr,
file_id,
AdjustmentCode,
PreferredvsNonPreferredBenefitLevel,
GeneralCategoryofHealthPlan,
LineofBusiness,
ClassificationCode,
BenefitIdentificationCode_BIC,
PlanCodeorExtensionofHierarchy,
BenefitTier,
FundingArrangement,
EmployeeSSN,
EmployeeLastName,
EmployeeFirstNameorInitial,
EmployeeGender,
EmployeeDateofBirth,
EmployeeZipCode,
EmployeeState,
CoverageEnrollmentTier,
MemberSSN,
MemberID_AssignedinDataWarehouse,
MemberNumber,
MemberLastName,
MemberFirstName,
MemberGender,
MemberRelationshiptoEmployee,
MemberDateofBirth,
Source_SpecificTransactionIDNumber,
ACASGenerationSegmentNumber,
ACASPointerBacktoPreviousGenSeg,
TraditionalClaimID,
ExpensePayLineNumber,
ClaimLineID_AssignedinDataWarehouse,
EmployeeNetworkID,
ServicingProviderNetworkID,
ReferralType,
PCPsIRSTaxIdentificationNumber_TINFormatCode,
PCPsIRSTaxIdentificationNumber_TIN,
PCPsName_LastorFull,
ServicingProviderTaxIDNumber_TINFormatCode,
ServicingProviderTaxIDNumber_TIN,
ServicingProviderPIN,
ServicingProviderName_LastorFull,
ServicingProviderStreetAddress1,
ServicingProviderStreetAddress2,
ServicingProviderCity,
ServicingProviderState,
ServicingProviderZipCode,
ServicingProviderType,
ServicingProviderSpecialtyCode,
AssignmentofBenefitstoProviderCode,
ParticipatingProviderCode,
DateClaimSubmissionReceived,
DateProcessed_Non_HMOOnly,
DateServiceStarted,
DateServiceStopped,
DateProcessed_All,
Filler1,
Filler2,
Filler3,
MajorDiagnosticCategory_MDC,
DiagnosisRelatedGroup_DRG,
LineLevelProcedureCode,
Line_LevelProcedureCodeModifier,
Line_LevelProcedureCodeType,
Filler4,
Filler5,
Filler6,
TypeofService,
ServiceBenefitCode,
ToothNumber,
PlaceofService,
UB92PatientDischargeStatus,
UB92RevenueCenter,
UB92BillType,
NumberUnitsofService,
SourceNumberUnitsofService,
GrossSubmittedExpense,
NetSubmittedExpense,
NotCoveredAmount1,
NotCoveredAmount2,
NotCoveredAmount3,
ActionorReasonCode1,
ActionorReasonCode2,
ActionorReasonCode3,
CoveredExpense,
AllowedAmount,
Filler7,
CopaymentAmount,
SourceCopaymentAmount,
DeductibleAmount,
Coinsurance,
SourceCoinsuranceAmount,
BenefitPayable,
PaidAmount,
COBPaidAmount,
AetnaHealthFundBeforeFundDeductible,
AetnaHealthFundPayableAmount,
Savings_NegotiatedFee,
SavingsR_and_C,
SavingsCOB,
SavingsSourceCOB,
MedicareCode,
TypeofExpenseCOB,
COBCode,
NationalDrugCode,
MemberCUMBID,
StatusofClaim,
Non_SSNEmployeeID,
ReversalCode,
AdmitCounter,
AdministrativeSavingsAmount,
AexcelProviderDesignationCode,
AexcelPlanDesignCode,
AexcelBenefitTierCode,
AexcelDesignatedProviderSpecialty,
ProductDistinctionCode,
BilledEligibleAmount_masked_donotusethisfield,
ServicingProviderClassCode,
PresentonAdmissionCode_1,
PresentonAdmissionCode_2,
PresentonAdmissionCode_3,
Filler8,
Filler9,
Filler10,
PricingMethodCode,
ServicingProviderTypeClassCode,
ServicingProviderSpecialtyCategoryCode,
ServicingProviderNPI,
TotalDeductibleMetIndicator,
TotalInterestAmount,
TotalSurchargeAmount,
Filler11,
HCFAPlaceofServiceCode,
HCFAAdmitSourceCode,
HCFAAdmitTypeCode,
AdmissionDate,
DischargeDate,
Line_LevelProcedureCodeModifier_2,
Line_LevelProcedureCodeModifier_3,
PresentonAdmissionCode_4,
PresentonAdmissionCode_5,
PresentonAdmissionCode_6,
PresentonAdmissionCode_7,
PresentonAdmissionCode_8,
PresentonAdmissionCode_9,
PresentonAdmissionCode_10,
DiagnosisCode1,
DiagnosisCode2,
DiagnosisCode3,
DiagnosisCode4,
DiagnosisCode5,
DiagnosisCode6,
DiagnosisCode7,
DiagnosisCode8,
DiagnosisCode9,
DiagnosisCode10,
ICDProcedureCode1,
ICDProcedureCode2,
ICDProcedureCode3,
ICDProcedureCode4,
ICDProcedureCode5,
ICDProcedureCode6,
AetnaHealthFundDeterminationOrderCode,
AetnaHealthFundMemberShareofCoinsuranceAmount,
AetnaHealthFundMemberCopayAmount,
AetnaHealthFundMemberDeductibleAmount,
Filler12,
Filler13,
ICD10Indicator,
ExchangeID,
Filler14,
EndofRecordMarker,
sourcefilename
)
select 
trim(split_part(rowdata,'\t',1)) as ps_unique_id,
trim(split_part(rowdata,'\t',2)) as customer_nbr,
trim(split_part(rowdata,'\t',3)) as group_nbr,
trim(split_part(rowdata,'\t',4)) as Filler,
trim(split_part(rowdata,'\t',5)) as subgroup_nbr,
trim(split_part(rowdata,'\t',6)) as account_nbr,
trim(split_part(rowdata,'\t',7)) as file_id,
trim(split_part(rowdata,'\t',8)) as AdjustmentCode,
trim(split_part(rowdata,'\t',9)) as PreferredvsNonPreferredBenefitLevel,
trim(split_part(rowdata,'\t',10)) as GeneralCategoryofHealthPlan,
trim(split_part(rowdata,'\t',11)) as LineofBusiness,
trim(split_part(rowdata,'\t',12)) as ClassificationCode,
trim(split_part(rowdata,'\t',13)) as BenefitIdentificationCode_BIC,
trim(split_part(rowdata,'\t',14)) as PlanCodeorExtensionofHierarchy,
trim(split_part(rowdata,'\t',15)) as BenefitTier,
trim(split_part(rowdata,'\t',16)) as FundingArrangement,
trim(split_part(rowdata,'\t',17)) as EmployeeSSN,
trim(split_part(rowdata,'\t',18)) as EmployeeLastName,
trim(split_part(rowdata,'\t',19)) as EmployeeFirstNameorInitial,
trim(split_part(rowdata,'\t',20)) as EmployeeGender,
trim(split_part(rowdata,'\t',21)) as EmployeeDateofBirth,
trim(split_part(rowdata,'\t',22)) as EmployeeZipCode,
trim(split_part(rowdata,'\t',23)) as EmployeeState,
trim(split_part(rowdata,'\t',24)) as CoverageEnrollmentTier,
trim(split_part(rowdata,'\t',25)) as MemberSSN,
trim(split_part(rowdata,'\t',26)) as MemberID_AssignedinDataWarehouse,
trim(split_part(rowdata,'\t',27)) as MemberNumber,
trim(split_part(rowdata,'\t',28)) as MemberLastName,
trim(split_part(rowdata,'\t',29)) as MemberFirstName,
trim(split_part(rowdata,'\t',30)) as MemberGender,
trim(split_part(rowdata,'\t',31)) as MemberRelationshiptoEmployee,
trim(split_part(rowdata,'\t',32)) as MemberDateofBirth,
trim(split_part(rowdata,'\t',33)) as Source_SpecificTransactionIDNumber,
trim(split_part(rowdata,'\t',34)) as ACASGenerationSegmentNumber,
trim(split_part(rowdata,'\t',35)) as ACASPointerBacktoPreviousGenSeg,
trim(split_part(rowdata,'\t',36)) as TraditionalClaimID,
trim(split_part(rowdata,'\t',37)) as ExpensePayLineNumber,
trim(split_part(rowdata,'\t',38)) as ClaimLineID_AssignedinDataWarehouse,
trim(split_part(rowdata,'\t',39)) as EmployeeNetworkID,
trim(split_part(rowdata,'\t',40)) as ServicingProviderNetworkID,
trim(split_part(rowdata,'\t',41)) as ReferralType,
trim(split_part(rowdata,'\t',42)) as PCPsIRSTaxIdentificationNumber_TINFormatCode,
trim(split_part(rowdata,'\t',43)) as PCPsIRSTaxIdentificationNumber_TIN,
trim(split_part(rowdata,'\t',44)) as PCPsName_LastorFull,
trim(split_part(rowdata,'\t',45)) as ServicingProviderTaxIDNumber_TINFormatCode,
trim(split_part(rowdata,'\t',46)) as ServicingProviderTaxIDNumber_TIN,
trim(split_part(rowdata,'\t',47)) as ServicingProviderPIN,
trim(split_part(rowdata,'\t',48)) as ServicingProviderName_LastorFull,
trim(split_part(rowdata,'\t',49)) as ServicingProviderStreetAddress1,
trim(split_part(rowdata,'\t',50)) as ServicingProviderStreetAddress2,
trim(split_part(rowdata,'\t',51)) as ServicingProviderCity,
trim(split_part(rowdata,'\t',52)) as ServicingProviderState,
trim(split_part(rowdata,'\t',53)) as ServicingProviderZipCode,
trim(split_part(rowdata,'\t',54)) as ServicingProviderType,
trim(split_part(rowdata,'\t',55)) as ServicingProviderSpecialtyCode,
trim(split_part(rowdata,'\t',56)) as AssignmentofBenefitstoProviderCode,
trim(split_part(rowdata,'\t',57)) as ParticipatingProviderCode,
trim(split_part(rowdata,'\t',58)) as DateClaimSubmissionReceived,
trim(split_part(rowdata,'\t',59)) as DateProcessed_Non_HMOOnly,
trim(split_part(rowdata,'\t',60)) as DateServiceStarted,
trim(split_part(rowdata,'\t',61)) as DateServiceStopped,
trim(split_part(rowdata,'\t',62)) as DateProcessed_All,
trim(split_part(rowdata,'\t',63)) as Filler1,
trim(split_part(rowdata,'\t',64)) as Filler2,
trim(split_part(rowdata,'\t',65)) as Filler3,
trim(split_part(rowdata,'\t',66)) as MajorDiagnosticCategory_MDC,
trim(split_part(rowdata,'\t',67)) as DiagnosisRelatedGroup_DRG,
trim(split_part(rowdata,'\t',68)) as LineLevelProcedureCode,
trim(split_part(rowdata,'\t',69)) as Line_LevelProcedureCodeModifier,
trim(split_part(rowdata,'\t',70)) as Line_LevelProcedureCodeType,
trim(split_part(rowdata,'\t',71)) as Filler4,
trim(split_part(rowdata,'\t',72)) as Filler5,
trim(split_part(rowdata,'\t',73)) as Filler6,
trim(split_part(rowdata,'\t',74)) as TypeofService,
trim(split_part(rowdata,'\t',75)) as ServiceBenefitCode,
trim(split_part(rowdata,'\t',76)) as ToothNumber,
trim(split_part(rowdata,'\t',77)) as PlaceofService,
trim(split_part(rowdata,'\t',78)) as UB92PatientDischargeStatus,
trim(split_part(rowdata,'\t',79)) as UB92RevenueCenter,
trim(split_part(rowdata,'\t',80)) as UB92BillType,
trim(split_part(rowdata,'\t',81)) as NumberUnitsofService,
trim(split_part(rowdata,'\t',82)) as SourceNumberUnitsofService,
trim(split_part(rowdata,'\t',83)) as GrossSubmittedExpense,
trim(split_part(rowdata,'\t',84)) as NetSubmittedExpense,
trim(split_part(rowdata,'\t',85)) as NotCoveredAmount1,
trim(split_part(rowdata,'\t',86)) as NotCoveredAmount2,
trim(split_part(rowdata,'\t',87)) as NotCoveredAmount3,
trim(split_part(rowdata,'\t',88)) as ActionorReasonCode1,
trim(split_part(rowdata,'\t',89)) as ActionorReasonCode2,
trim(split_part(rowdata,'\t',90)) as ActionorReasonCode3,
trim(split_part(rowdata,'\t',91)) as CoveredExpense,
trim(split_part(rowdata,'\t',92)) as AllowedAmount,
trim(split_part(rowdata,'\t',93)) as Filler7,
trim(split_part(rowdata,'\t',94)) as CopaymentAmount,
trim(split_part(rowdata,'\t',95)) as SourceCopaymentAmount,
trim(split_part(rowdata,'\t',96)) as DeductibleAmount,
trim(split_part(rowdata,'\t',97)) as Coinsurance,
trim(split_part(rowdata,'\t',98)) as SourceCoinsuranceAmount,
trim(split_part(rowdata,'\t',99)) as BenefitPayable,
trim(split_part(rowdata,'\t',100)) as PaidAmount,
trim(split_part(rowdata,'\t',101)) as COBPaidAmount,
trim(split_part(rowdata,'\t',102)) as AetnaHealthFundBeforeFundDeductible,
trim(split_part(rowdata,'\t',103)) as AetnaHealthFundPayableAmount,
trim(split_part(rowdata,'\t',104)) as Savings_NegotiatedFee,
trim(split_part(rowdata,'\t',105)) as SavingsR_and_C,
trim(split_part(rowdata,'\t',106)) as SavingsCOB,
trim(split_part(rowdata,'\t',107)) as SavingsSourceCOB,
trim(split_part(rowdata,'\t',108)) as MedicareCode,
trim(split_part(rowdata,'\t',109)) as TypeofExpenseCOB,
trim(split_part(rowdata,'\t',110)) as COBCode,
trim(split_part(rowdata,'\t',111)) as NationalDrugCode,
trim(split_part(rowdata,'\t',112)) as MemberCUMBID,
trim(split_part(rowdata,'\t',113)) as StatusofClaim,
trim(split_part(rowdata,'\t',114)) as Non_SSNEmployeeID,
trim(split_part(rowdata,'\t',115)) as ReversalCode,
trim(split_part(rowdata,'\t',116)) as AdmitCounter,
trim(split_part(rowdata,'\t',117)) as AdministrativeSavingsAmount,
trim(split_part(rowdata,'\t',118)) as AexcelProviderDesignationCode,
trim(split_part(rowdata,'\t',119)) as AexcelPlanDesignCode,
trim(split_part(rowdata,'\t',120)) as AexcelBenefitTierCode,
trim(split_part(rowdata,'\t',121)) as AexcelDesignatedProviderSpecialty,
trim(split_part(rowdata,'\t',122)) as ProductDistinctionCode,
trim(split_part(rowdata,'\t',123)) as BilledEligibleAmount_masked_donotusethisfield,
trim(split_part(rowdata,'\t',124)) as ServicingProviderClassCode,
trim(split_part(rowdata,'\t',125)) as PresentonAdmissionCode_1,
trim(split_part(rowdata,'\t',126)) as PresentonAdmissionCode_2,
trim(split_part(rowdata,'\t',127)) as PresentonAdmissionCode_3,
trim(split_part(rowdata,'\t',128)) as Filler8,
trim(split_part(rowdata,'\t',129)) as Filler9,
trim(split_part(rowdata,'\t',130)) as Filler10,
trim(split_part(rowdata,'\t',131)) as PricingMethodCode,
trim(split_part(rowdata,'\t',132)) as ServicingProviderTypeClassCode,
trim(split_part(rowdata,'\t',133)) as ServicingProviderSpecialtyCategoryCode,
trim(split_part(rowdata,'\t',134)) as ServicingProviderNPI,
trim(split_part(rowdata,'\t',135)) as TotalDeductibleMetIndicator,
trim(split_part(rowdata,'\t',136)) as TotalInterestAmount,
trim(split_part(rowdata,'\t',137)) as TotalSurchargeAmount,
trim(split_part(rowdata,'\t',138)) as Filler11,
trim(split_part(rowdata,'\t',139)) as HCFAPlaceofServiceCode,
trim(split_part(rowdata,'\t',140)) as HCFAAdmitSourceCode,
trim(split_part(rowdata,'\t',141)) as HCFAAdmitTypeCode,
trim(split_part(rowdata,'\t',142)) as AdmissionDate,
trim(split_part(rowdata,'\t',143)) as DischargeDate,
trim(split_part(rowdata,'\t',144)) as Line_LevelProcedureCodeModifier_2,
trim(split_part(rowdata,'\t',145)) as Line_LevelProcedureCodeModifier_3,
trim(split_part(rowdata,'\t',146)) as PresentonAdmissionCode_4,
trim(split_part(rowdata,'\t',147)) as PresentonAdmissionCode_5,
trim(split_part(rowdata,'\t',148)) as PresentonAdmissionCode_6,
trim(split_part(rowdata,'\t',149)) as PresentonAdmissionCode_7,
trim(split_part(rowdata,'\t',150)) as PresentonAdmissionCode_8,
trim(split_part(rowdata,'\t',151)) as PresentonAdmissionCode_9,
trim(split_part(rowdata,'\t',152)) as PresentonAdmissionCode_10,
trim(split_part(rowdata,'\t',153)) as DiagnosisCode1,
trim(split_part(rowdata,'\t',154)) as DiagnosisCode2,
trim(split_part(rowdata,'\t',155)) as DiagnosisCode3,
trim(split_part(rowdata,'\t',156)) as DiagnosisCode4,
trim(split_part(rowdata,'\t',157)) as DiagnosisCode5,
trim(split_part(rowdata,'\t',158)) as DiagnosisCode6,
trim(split_part(rowdata,'\t',159)) as DiagnosisCode7,
trim(split_part(rowdata,'\t',160)) as DiagnosisCode8,
trim(split_part(rowdata,'\t',161)) as DiagnosisCode9,
trim(split_part(rowdata,'\t',162)) as DiagnosisCode10,
trim(split_part(rowdata,'\t',163)) as ICDProcedureCode1,
trim(split_part(rowdata,'\t',164)) as ICDProcedureCode2,
trim(split_part(rowdata,'\t',165)) as ICDProcedureCode3,
trim(split_part(rowdata,'\t',166)) as ICDProcedureCode4,
trim(split_part(rowdata,'\t',167)) as ICDProcedureCode5,
trim(split_part(rowdata,'\t',168)) as ICDProcedureCode6,
trim(split_part(rowdata,'\t',169)) as AetnaHealthFundDeterminationOrderCode,
trim(split_part(rowdata,'\t',170)) as AetnaHealthFundMemberShareofCoinsuranceAmount,
trim(split_part(rowdata,'\t',171)) as AetnaHealthFundMemberCopayAmount,
trim(split_part(rowdata,'\t',172)) as AetnaHealthFundMemberDeductibleAmount,
trim(split_part(rowdata,'\t',173)) as Filler12,
trim(split_part(rowdata,'\t',174)) as Filler13,
trim(split_part(rowdata,'\t',175)) as ICD10Indicator,
trim(split_part(rowdata,'\t',176)) as ExchangeID,
trim(split_part(rowdata,'\t',177)) as Filler14,
trim(split_part(rowdata,'\t',178)) as EndofRecordMarker,
'90932834-UMED_CLMDATA___20161001_20161031.txt' as sourcefilename
from raw_tfk.temp_tfk_ethos_med_20161118;


select * from raw_tfk.rstag_tfk_ethos_med_20161118 limit 100;
